// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARVNcGiHQ0jgb20Jch2wxmPu2oGc20Ypk',
    appId: '1:864036256863:web:e2a16f7525e3a26e69efea',
    messagingSenderId: '864036256863',
    projectId: 'bookmyspace2025',
    authDomain: 'bookmyspace2025.firebaseapp.com',
    storageBucket: 'bookmyspace2025.firebasestorage.app',
    measurementId: 'G-8V0Z1DMBP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1-EJUOpQ0W8l5VJdQ5o2FhybKCfigVQ',
    appId: '1:864036256863:android:eb6e996bdaa4f8a969efea',
    messagingSenderId: '864036256863',
    projectId: 'bookmyspace2025',
    storageBucket: 'bookmyspace2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Ekh-FsX_Rzc9Lb7JhiSGiQXeFtYgj-E',
    appId: '1:864036256863:ios:6601e2c742fb8eb869efea',
    messagingSenderId: '864036256863',
    projectId: 'bookmyspace2025',
    storageBucket: 'bookmyspace2025.firebasestorage.app',
    iosClientId: '864036256863-os0a7nl5p8el8bdv2ngruqjbcfo31j4d.apps.googleusercontent.com',
    iosBundleId: 'com.bookmyspace.bookMySpace',
  );
}
