import { IsEmail, IsString, MinLength, IsEnum, IsOptional, IsMobilePhone } from 'class-validator';
import { Role } from '@prisma/client';

export class RegisterDto {
  @IsString()
  name: string;

  @IsEmail()
  email: string;

  @IsMobilePhone('en-IN')
  @IsOptional()
  phone?: string;

  @IsString()
  @MinLength(8)
  password: string;

  // Only CUSTOMER or MANAGER allowed via public register
  @IsEnum([Role.CUSTOMER, Role.MANAGER])
  role: Role;

  // Manager-specific
  @IsString()
  @IsOptional()
  businessName?: string;

  // Customer-specific: referral
  @IsString()
  @IsOptional()
  referralCode?: string;
}

export class LoginDto {
  @IsEmail()
  email: string;

  @IsString()
  password: string;
}

export class StaffRegisterDto {
  @IsString()
  name: string;

  @IsEmail()
  email: string;

  @IsString()
  @MinLength(8)
  password: string;

  @IsString()
  staffCode: string; // 8-char code generated by manager
}

export class RefreshTokenDto {
  @IsString()
  refreshToken: string;
}

export class ChangePasswordDto {
  @IsString()
  currentPassword: string;

  @IsString()
  @MinLength(8)
  newPassword: string;
}

export class ForgotPasswordDto {
  @IsEmail()
  email: string;
}

export class ResetPasswordDto {
  @IsString()
  token: string;

  @IsString()
  @MinLength(8)
  newPassword: string;
}
